### ISSUE TITLE
No PySide Autocompletion

### ISSUE THREAD

**Issue by tamulionis** [DamnWidget/SublimePySide#7]
Installed this and SublimePythonIDE, but autocompletion for PySide and PyQT4 doesn't work.

**Comment by DamnWidget** [comment]
Hi @tamulionis 

You have to make sure that your configured python interpreter can see PyQt4 and PySide, that means, those packages are installed in the same environment than your configured python interpreter. And remember that ST3 uses it self built-in python 3 interpreter and environment.

Refer here https://github.com/JulianEberius/SublimePythonIDE#configuration for more information.

**Comment by tamulionis** [comment]
Project configuration file looks like this, but still no autocompletion. Is it necessary to use virtualenv?
{
    "folders":
    [
        {
            "follow_symlinks": true,
            "path": "/media/stuff/Python/abc"
        }
    ],
    "settings":
    {
        "python_interpreter": "/usr/bin/python3"
    }
}

**Comment by DamnWidget** [comment]
What happens if you execute this into the /usr/bin/python3 interpreter terminal?

```
import PyQt4
import PySide
```

**Comment by tamulionis** [comment]
Everything imports correctly

**Comment by DamnWidget** [comment]
In that case SublimePython should make it available for auto completion. SublimePySide doesn't give you any autocompletion support by itself. In ST2 and if SublimeRope is present, it will autogenerate a `.sublimerope` project in the new generated PySide ot PyQt4 project but has really nothing to do with SublimePython or SublimeJEDI.

I suggest you to open a ticket in the SublimePython project directly as the problem is really related with SublimePython not being able to autocomplete PySide or PyQt4 bindings.

Regards.

**Comment by tamulionis** [comment]
Ok. Just thought that the problem is on this end, cause autocompletion for other things works.

**Comment by DamnWidget** [comment]
I'm sorry to can't be more helpful here.

Good luck!

**Comment by DamnWidget** [comment]
Hey @tamulionis 

I have written a new plugin that offers just autocompletion (based on Jedi library) and Lintin of Python projects. The plugin is called "anaconda" (I know but I am not a creative person) and you can find it in my repositories:

https://github.com/DamnWidget/anaconda

This is just the plugin that I am using now instead of SublimePythonIDE it has the same functionallity than SublimeJEDI and SublimeLinter.

It´s so fast on Linux but I felt it a bit slower on Windows (I don´t know why really).

Regards.
